################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F2xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
LWIP/App \
LWIP/Target \
Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/http \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/apps/sntp \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/system/OS \
RTT \
SPI_Flash \
USB_DEVICE/App \
USB_DEVICE/Target \
app_btn \
app_cli \
app_debug \
app_ethernet \
app_http \
app_msc_cdc \
indicator \
lwrb \
min_protocol \
tinyusb-master/src/class/audio \
tinyusb-master/src/class/bth \
tinyusb-master/src/class/cdc \
tinyusb-master/src/class/dfu \
tinyusb-master/src/class/hid \
tinyusb-master/src/class/midi \
tinyusb-master/src/class/msc \
tinyusb-master/src/class/net \
tinyusb-master/src/class/usbtmc \
tinyusb-master/src/class/vendor \
tinyusb-master/src/class/video \
tinyusb-master/src/common \
tinyusb-master/src/device \
tinyusb-master/src/host \
tinyusb-master/src/portable/bridgetek/ft9xx \
tinyusb-master/src/portable/broadcom/synopsys \
tinyusb-master/src/portable/chipidea/ci_hs \
tinyusb-master/src/portable/dialog/da146xx \
tinyusb-master/src/portable/ehci \
tinyusb-master/src/portable/espressif/esp32sx \
tinyusb-master/src/portable/mentor/musb \
tinyusb-master/src/portable/microchip/pic32mz \
tinyusb-master/src/portable/microchip/samd \
tinyusb-master/src/portable/microchip/samg \
tinyusb-master/src/portable/microchip/samx7x \
tinyusb-master/src/portable/mindmotion/mm32 \
tinyusb-master/src/portable/nordic/nrf5x \
tinyusb-master/src/portable/nuvoton/nuc120 \
tinyusb-master/src/portable/nuvoton/nuc121 \
tinyusb-master/src/portable/nuvoton/nuc505 \
tinyusb-master/src/portable/nxp/khci \
tinyusb-master/src/portable/nxp/lpc17_40 \
tinyusb-master/src/portable/nxp/lpc_ip3511 \
tinyusb-master/src/portable/nxp/transdimension \
tinyusb-master/src/portable/ohci \
tinyusb-master/src/portable/raspberrypi/rp2040 \
tinyusb-master/src/portable/renesas/usba \
tinyusb-master/src/portable/sony/cxd56 \
tinyusb-master/src/portable/sunxi \
tinyusb-master/src/portable/synopsys/dwc2 \
tinyusb-master/src/portable/template \
tinyusb-master/src/portable/ti/msp430x5xx \
tinyusb-master/src/portable/valentyusb/eptri \
tinyusb-master/src \
u8g2 \
utilities \

